image: python:3.6-alpine

stages:
  - deploy

before_script:
   - pip install sphinx_autodoc_typehints
   - pip install sphinx_rtd_theme
   - pip install sphinx_paramlinks
   - pip install twine
   - python setup.py sdist

deploy_staging:
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  except:
    - tags
